pipeline {
agent any
  stages {
    stage('SSH') {
      steps {
        sshPublisher(
          continueOnError: true,
          failOnError: true,
          publishers: [
            sshPublisherDesc(
              configName: 'remote',
              verbose: true,
              transfers: [
                sshTransfer(execCommand: 'ls -al /root'),
                sshTransfer(execCommand: 'pwd')
              ]
            )
          ]
        )
      }
    }
  }
    post {
        always {
            cleanWs()
        }
        success {
            echo 'Build successful!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
