pipeline {
    agent any
    stages {
        stage('Download') {
            steps {
                sh 'echo Done2'
            }
        }
        stage('SSH to remote server and execute command') {
            steps {
                sshScript remote: [
                    host: env.REMOTE_HOST, 
                    port: env.REMOTE_PORT.toInteger(), 
                    credentialsId: 'ssh-credentials-id'
                ], script: 'ls -al'
            }
        }
    }
    post {
        always {
            cleanWs()
        }
        success {
            echo 'Build successful!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
