pipeline {
    agent any
    stages {
        stage('SSH') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'ssh-credentials-id', keyFileVariable: 'SSH_KEYFILE',
                                                    passphraseVariable: 'SSH_PASSPHRASE', usernameVariable: 'SSH_USERNAME')]) {

                    script {
                        sh """
                        ssh -o "StrictHostKeyChecking=no" -o "PasswordAuthentication=yes" -o "PreferredAuthentications=password" -o "PubkeyAuthentication=no" ${SSH_USERNAME}@${REMOTE_HOST} env PASSWORD="3237258mM" << EOF
                            ls -l
                            pwd
                            exit 0
                        << EOF
                        """
                }
                }
            }
        }

    }
    post {
        always {
            cleanWs()
        }
        success {
            echo 'Build successful!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
